-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 05, 2025 at 08:50 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `blog`
--

-- --------------------------------------------------------

--
-- Table structure for table `article`
--

CREATE TABLE `article` (
  `idarticle` int(11) NOT NULL,
  `title` varchar(100) NOT NULL,
  `releasedate` datetime NOT NULL,
  `content` varchar(5000) NOT NULL,
  `category` varchar(100) NOT NULL,
  `image` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `article`
--

INSERT INTO `article` (`idarticle`, `title`, `releasedate`, `content`, `category`, `image`) VALUES
(7, 'Duis Id Elementum Magna, Vel Viverra Nisl.', '2025-10-05 11:57:30', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed hendrerit dui sed odio elementum, et lacinia ipsum posuere. Pellentesque tortor ex, fringilla eget auctor nec, efficitur id quam. Nulla facilisi. Morbi in auctor dolor, porttitor posuere tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer lobortis scelerisque urna. Pellentesque volutpat mauris quis arcu cursus sollicitudin.\r\n\r\nInteger cursus eget lacus sit amet porttitor. Mauris tristique elementum ante et maximus. Duis egestas tempus ante, et vestibulum metus sollicitudin vitae. Quisque faucibus mauris neque, ut venenatis libero vehicula quis. Quisque maximus turpis neque, et tempus velit tempus eu. Aliquam euismod venenatis justo non tincidunt. Donec ornare, elit sed condimentum congue, turpis odio dapibus felis, et varius enim odio ut lacus. Vestibulum id leo quis sem pulvinar sollicitudin vel nec ante. Pellentesque quis euismod lacus, non sodales urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer hendrerit in elit eu aliquam. Vivamus et commodo arcu, ac facilisis ipsum. Sed non suscipit risus, et lacinia justo. Fusce vel ipsum lacus.\r\n\r\nDonec dictum dui diam, tristique mollis justo fermentum in. Donec in leo tellus. Nunc efficitur tortor ut nisl laoreet, quis rutrum ipsum varius. Nunc ullamcorper lobortis neque, ac volutpat enim tincidunt quis. Cras ornare magna vitae egestas convallis. Proin a erat sed lorem lacinia dictum ut et lorem. Donec dapibus sagittis ipsum, vel iaculis ante ultricies tincidunt. Nunc elementum nisl sed enim tempus mattis. Sed finibus nec lectus sed tristique.\r\n\r\nPhasellus eros est, dapibus sed vulputate non, laoreet ac odio. Vivamus venenatis auctor ultrices. Phasellus vestibulum porta elit, id gravida sem ultricies et. Aliquam quis ex vel eros finibus porttitor. Fusce eu rutrum quam. Nunc vel nisl leo. Phasellus scelerisque convallis est, vel varius lectus molestie quis. Pellentesque non tempus lorem. Proin interdum dui vel urna ultricies faucibus. Suspendisse turpis est, varius ut nibh vel, posuere tempor risus. Nulla scelerisque dictum congue.\r\n\r\nDuis id elementum magna, vel viverra nisl. In posuere et lorem vitae iaculis. Mauris et dapibus massa, ac tempus arcu. Donec eu ipsum vitae lorem elementum varius. Fusce egestas est tortor, eget egestas massa tristique id. Sed eu pellentesque neque. Praesent in lacus sem. Maecenas lobortis porttitor magna ac elementum. Praesent laoreet turpis eu enim placerat vestibulum. Ut eleifend fringilla massa ut porttitor. Integer pretium purus nec vulputate gravida. Curabitur mattis tincidunt ipsum, ac rutrum erat egestas vestibulum.', 'Coding', '1759646958_code web.png'),
(8, 'Fusce Eu Rutrum Quam', '2025-10-05 12:01:02', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed hendrerit dui sed odio elementum, et lacinia ipsum posuere. Pellentesque tortor ex, fringilla eget auctor nec, efficitur id quam. Nulla facilisi. Morbi in auctor dolor, porttitor posuere tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer lobortis scelerisque urna. Pellentesque volutpat mauris quis arcu cursus sollicitudin.\r\n\r\nInteger cursus eget lacus sit amet porttitor. Mauris tristique elementum ante et maximus. Duis egestas tempus ante, et vestibulum metus sollicitudin vitae. Quisque faucibus mauris neque, ut venenatis libero vehicula quis. Quisque maximus turpis neque, et tempus velit tempus eu. Aliquam euismod venenatis justo non tincidunt. Donec ornare, elit sed condimentum congue, turpis odio dapibus felis, et varius enim odio ut lacus. Vestibulum id leo quis sem pulvinar sollicitudin vel nec ante. Pellentesque quis euismod lacus, non sodales urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer hendrerit in elit eu aliquam. Vivamus et commodo arcu, ac facilisis ipsum. Sed non suscipit risus, et lacinia justo. Fusce vel ipsum lacus.\r\n\r\nDonec dictum dui diam, tristique mollis justo fermentum in. Donec in leo tellus. Nunc efficitur tortor ut nisl laoreet, quis rutrum ipsum varius. Nunc ullamcorper lobortis neque, ac volutpat enim tincidunt quis. Cras ornare magna vitae egestas convallis. Proin a erat sed lorem lacinia dictum ut et lorem. Donec dapibus sagittis ipsum, vel iaculis ante ultricies tincidunt. Nunc elementum nisl sed enim tempus mattis. Sed finibus nec lectus sed tristique.\r\n\r\nPhasellus eros est, dapibus sed vulputate non, laoreet ac odio. Vivamus venenatis auctor ultrices. Phasellus vestibulum porta elit, id gravida sem ultricies et. Aliquam quis ex vel eros finibus porttitor. Fusce eu rutrum quam. Nunc vel nisl leo. Phasellus scelerisque convallis est, vel varius lectus molestie quis. Pellentesque non tempus lorem. Proin interdum dui vel urna ultricies faucibus. Suspendisse turpis est, varius ut nibh vel, posuere tempor risus. Nulla scelerisque dictum congue.\r\n\r\nDuis id elementum magna, vel viverra nisl. In posuere et lorem vitae iaculis. Mauris et dapibus massa, ac tempus arcu. Donec eu ipsum vitae lorem elementum varius. Fusce egestas est tortor, eget egestas massa tristique id. Sed eu pellentesque neque. Praesent in lacus sem. Maecenas lobortis porttitor magna ac elementum. Praesent laoreet turpis eu enim placerat vestibulum. Ut eleifend fringilla massa ut porttitor. Integer pretium purus nec vulputate gravida. Curabitur mattis tincidunt ipsum, ac rutrum erat egestas vestibulum.', 'culinary', '1759646943_kue.jpg'),
(9, 'Donec In Leo Tellus', '2025-10-05 12:02:25', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed hendrerit dui sed odio elementum, et lacinia ipsum posuere. Pellentesque tortor ex, fringilla eget auctor nec, efficitur id quam. Nulla facilisi. Morbi in auctor dolor, porttitor posuere tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer lobortis scelerisque urna. Pellentesque volutpat mauris quis arcu cursus sollicitudin.\r\n\r\nInteger cursus eget lacus sit amet porttitor. Mauris tristique elementum ante et maximus. Duis egestas tempus ante, et vestibulum metus sollicitudin vitae. Quisque faucibus mauris neque, ut venenatis libero vehicula quis. Quisque maximus turpis neque, et tempus velit tempus eu. Aliquam euismod venenatis justo non tincidunt. Donec ornare, elit sed condimentum congue, turpis odio dapibus felis, et varius enim odio ut lacus. Vestibulum id leo quis sem pulvinar sollicitudin vel nec ante. Pellentesque quis euismod lacus, non sodales urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer hendrerit in elit eu aliquam. Vivamus et commodo arcu, ac facilisis ipsum. Sed non suscipit risus, et lacinia justo. Fusce vel ipsum lacus.\r\n\r\nDonec dictum dui diam, tristique mollis justo fermentum in. Donec in leo tellus. Nunc efficitur tortor ut nisl laoreet, quis rutrum ipsum varius. Nunc ullamcorper lobortis neque, ac volutpat enim tincidunt quis. Cras ornare magna vitae egestas convallis. Proin a erat sed lorem lacinia dictum ut et lorem. Donec dapibus sagittis ipsum, vel iaculis ante ultricies tincidunt. Nunc elementum nisl sed enim tempus mattis. Sed finibus nec lectus sed tristique.\r\n\r\nPhasellus eros est, dapibus sed vulputate non, laoreet ac odio. Vivamus venenatis auctor ultrices. Phasellus vestibulum porta elit, id gravida sem ultricies et. Aliquam quis ex vel eros finibus porttitor. Fusce eu rutrum quam. Nunc vel nisl leo. Phasellus scelerisque convallis est, vel varius lectus molestie quis. Pellentesque non tempus lorem. Proin interdum dui vel urna ultricies faucibus. Suspendisse turpis est, varius ut nibh vel, posuere tempor risus. Nulla scelerisque dictum congue.\r\n\r\nDuis id elementum magna, vel viverra nisl. In posuere et lorem vitae iaculis. Mauris et dapibus massa, ac tempus arcu. Donec eu ipsum vitae lorem elementum varius. Fusce egestas est tortor, eget egestas massa tristique id. Sed eu pellentesque neque. Praesent in lacus sem. Maecenas lobortis porttitor magna ac elementum. Praesent laoreet turpis eu enim placerat vestibulum. Ut eleifend fringilla massa ut porttitor. Integer pretium purus nec vulputate gravida. Curabitur mattis tincidunt ipsum, ac rutrum erat egestas vestibulum.', 'culinary', '1759646927_minuman.jpg'),
(10, 'Suspendisse Turpis Est, Varius Ut Nibh Vel, Posuere Tempor Risus', '2025-10-05 12:04:50', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed hendrerit dui sed odio elementum, et lacinia ipsum posuere. Pellentesque tortor ex, fringilla eget auctor nec, efficitur id quam. Nulla facilisi. Morbi in auctor dolor, porttitor posuere tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer lobortis scelerisque urna. Pellentesque volutpat mauris quis arcu cursus sollicitudin.\r\n\r\nInteger cursus eget lacus sit amet porttitor. Mauris tristique elementum ante et maximus. Duis egestas tempus ante, et vestibulum metus sollicitudin vitae. Quisque faucibus mauris neque, ut venenatis libero vehicula quis. Quisque maximus turpis neque, et tempus velit tempus eu. Aliquam euismod venenatis justo non tincidunt. Donec ornare, elit sed condimentum congue, turpis odio dapibus felis, et varius enim odio ut lacus. Vestibulum id leo quis sem pulvinar sollicitudin vel nec ante. Pellentesque quis euismod lacus, non sodales urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer hendrerit in elit eu aliquam. Vivamus et commodo arcu, ac facilisis ipsum. Sed non suscipit risus, et lacinia justo. Fusce vel ipsum lacus.\r\n\r\nDonec dictum dui diam, tristique mollis justo fermentum in. Donec in leo tellus. Nunc efficitur tortor ut nisl laoreet, quis rutrum ipsum varius. Nunc ullamcorper lobortis neque, ac volutpat enim tincidunt quis. Cras ornare magna vitae egestas convallis. Proin a erat sed lorem lacinia dictum ut et lorem. Donec dapibus sagittis ipsum, vel iaculis ante ultricies tincidunt. Nunc elementum nisl sed enim tempus mattis. Sed finibus nec lectus sed tristique.\r\n\r\nPhasellus eros est, dapibus sed vulputate non, laoreet ac odio. Vivamus venenatis auctor ultrices. Phasellus vestibulum porta elit, id gravida sem ultricies et. Aliquam quis ex vel eros finibus porttitor. Fusce eu rutrum quam. Nunc vel nisl leo. Phasellus scelerisque convallis est, vel varius lectus molestie quis. Pellentesque non tempus lorem. Proin interdum dui vel urna ultricies faucibus. Suspendisse turpis est, varius ut nibh vel, posuere tempor risus. Nulla scelerisque dictum congue.\r\n\r\nDuis id elementum magna, vel viverra nisl. In posuere et lorem vitae iaculis. Mauris et dapibus massa, ac tempus arcu. Donec eu ipsum vitae lorem elementum varius. Fusce egestas est tortor, eget egestas massa tristique id. Sed eu pellentesque neque. Praesent in lacus sem. Maecenas lobortis porttitor magna ac elementum. Praesent laoreet turpis eu enim placerat vestibulum. Ut eleifend fringilla massa ut porttitor. Integer pretium purus nec vulputate gravida. Curabitur mattis tincidunt ipsum, ac rutrum erat egestas vestibulum.', 'travel', '1759646913_pantai.jpeg'),
(11, 'Proin Interdum Dui Vel Urna Ultricies Faucibus', '2025-10-05 12:25:52', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed hendrerit dui sed odio elementum, et lacinia ipsum posuere. Pellentesque tortor ex, fringilla eget auctor nec, efficitur id quam. Nulla facilisi. Morbi in auctor dolor, porttitor posuere tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer lobortis scelerisque urna. Pellentesque volutpat mauris quis arcu cursus sollicitudin.\r\n\r\nInteger cursus eget lacus sit amet porttitor. Mauris tristique elementum ante et maximus. Duis egestas tempus ante, et vestibulum metus sollicitudin vitae. Quisque faucibus mauris neque, ut venenatis libero vehicula quis. Quisque maximus turpis neque, et tempus velit tempus eu. Aliquam euismod venenatis justo non tincidunt. Donec ornare, elit sed condimentum congue, turpis odio dapibus felis, et varius enim odio ut lacus. Vestibulum id leo quis sem pulvinar sollicitudin vel nec ante. Pellentesque quis euismod lacus, non sodales urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer hendrerit in elit eu aliquam. Vivamus et commodo arcu, ac facilisis ipsum. Sed non suscipit risus, et lacinia justo. Fusce vel ipsum lacus.\r\n\r\nDonec dictum dui diam, tristique mollis justo fermentum in. Donec in leo tellus. Nunc efficitur tortor ut nisl laoreet, quis rutrum ipsum varius. Nunc ullamcorper lobortis neque, ac volutpat enim tincidunt quis. Cras ornare magna vitae egestas convallis. Proin a erat sed lorem lacinia dictum ut et lorem. Donec dapibus sagittis ipsum, vel iaculis ante ultricies tincidunt. Nunc elementum nisl sed enim tempus mattis. Sed finibus nec lectus sed tristique.\r\n\r\nPhasellus eros est, dapibus sed vulputate non, laoreet ac odio. Vivamus venenatis auctor ultrices. Phasellus vestibulum porta elit, id gravida sem ultricies et. Aliquam quis ex vel eros finibus porttitor. Fusce eu rutrum quam. Nunc vel nisl leo. Phasellus scelerisque convallis est, vel varius lectus molestie quis. Pellentesque non tempus lorem. Proin interdum dui vel urna ultricies faucibus. Suspendisse turpis est, varius ut nibh vel, posuere tempor risus. Nulla scelerisque dictum congue.\r\n\r\nDuis id elementum magna, vel viverra nisl. In posuere et lorem vitae iaculis. Mauris et dapibus massa, ac tempus arcu. Donec eu ipsum vitae lorem elementum varius. Fusce egestas est tortor, eget egestas massa tristique id. Sed eu pellentesque neque. Praesent in lacus sem. Maecenas lobortis porttitor magna ac elementum. Praesent laoreet turpis eu enim placerat vestibulum. Ut eleifend fringilla massa ut porttitor. Integer pretium purus nec vulputate gravida. Curabitur mattis tincidunt ipsum, ac rutrum erat egestas vestibulum.', 'education', '1759646896_perpus.webp'),
(12, 'Maecenas Lobortis Porttitor Magna Ac Elementum', '2025-10-05 12:31:20', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed hendrerit dui sed odio elementum, et lacinia ipsum posuere. Pellentesque tortor ex, fringilla eget auctor nec, efficitur id quam. Nulla facilisi. Morbi in auctor dolor, porttitor posuere tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer lobortis scelerisque urna. Pellentesque volutpat mauris quis arcu cursus sollicitudin.\r\n\r\nInteger cursus eget lacus sit amet porttitor. Mauris tristique elementum ante et maximus. Duis egestas tempus ante, et vestibulum metus sollicitudin vitae. Quisque faucibus mauris neque, ut venenatis libero vehicula quis. Quisque maximus turpis neque, et tempus velit tempus eu. Aliquam euismod venenatis justo non tincidunt. Donec ornare, elit sed condimentum congue, turpis odio dapibus felis, et varius enim odio ut lacus. Vestibulum id leo quis sem pulvinar sollicitudin vel nec ante. Pellentesque quis euismod lacus, non sodales urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer hendrerit in elit eu aliquam. Vivamus et commodo arcu, ac facilisis ipsum. Sed non suscipit risus, et lacinia justo. Fusce vel ipsum lacus.\r\n\r\nDonec dictum dui diam, tristique mollis justo fermentum in. Donec in leo tellus. Nunc efficitur tortor ut nisl laoreet, quis rutrum ipsum varius. Nunc ullamcorper lobortis neque, ac volutpat enim tincidunt quis. Cras ornare magna vitae egestas convallis. Proin a erat sed lorem lacinia dictum ut et lorem. Donec dapibus sagittis ipsum, vel iaculis ante ultricies tincidunt. Nunc elementum nisl sed enim tempus mattis. Sed finibus nec lectus sed tristique.\r\n\r\nPhasellus eros est, dapibus sed vulputate non, laoreet ac odio. Vivamus venenatis auctor ultrices. Phasellus vestibulum porta elit, id gravida sem ultricies et. Aliquam quis ex vel eros finibus porttitor. Fusce eu rutrum quam. Nunc vel nisl leo. Phasellus scelerisque convallis est, vel varius lectus molestie quis. Pellentesque non tempus lorem. Proin interdum dui vel urna ultricies faucibus. Suspendisse turpis est, varius ut nibh vel, posuere tempor risus. Nulla scelerisque dictum congue.\r\n\r\nDuis id elementum magna, vel viverra nisl. In posuere et lorem vitae iaculis. Mauris et dapibus massa, ac tempus arcu. Donec eu ipsum vitae lorem elementum varius. Fusce egestas est tortor, eget egestas massa tristique id. Sed eu pellentesque neque. Praesent in lacus sem. Maecenas lobortis porttitor magna ac elementum. Praesent laoreet turpis eu enim placerat vestibulum. Ut eleifend fringilla massa ut porttitor. Integer pretium purus nec vulputate gravida. Curabitur mattis tincidunt ipsum, ac rutrum erat egestas vestibulum.', 'coding', '1759646880_game.webp'),
(13, 'Vivamus Venenatis Auctor Ultrices', '2025-10-05 12:32:53', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed hendrerit dui sed odio elementum, et lacinia ipsum posuere. Pellentesque tortor ex, fringilla eget auctor nec, efficitur id quam. Nulla facilisi. Morbi in auctor dolor, porttitor posuere tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer lobortis scelerisque urna. Pellentesque volutpat mauris quis arcu cursus sollicitudin.\r\n\r\nInteger cursus eget lacus sit amet porttitor. Mauris tristique elementum ante et maximus. Duis egestas tempus ante, et vestibulum metus sollicitudin vitae. Quisque faucibus mauris neque, ut venenatis libero vehicula quis. Quisque maximus turpis neque, et tempus velit tempus eu. Aliquam euismod venenatis justo non tincidunt. Donec ornare, elit sed condimentum congue, turpis odio dapibus felis, et varius enim odio ut lacus. Vestibulum id leo quis sem pulvinar sollicitudin vel nec ante. Pellentesque quis euismod lacus, non sodales urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer hendrerit in elit eu aliquam. Vivamus et commodo arcu, ac facilisis ipsum. Sed non suscipit risus, et lacinia justo. Fusce vel ipsum lacus.\r\n\r\nDonec dictum dui diam, tristique mollis justo fermentum in. Donec in leo tellus. Nunc efficitur tortor ut nisl laoreet, quis rutrum ipsum varius. Nunc ullamcorper lobortis neque, ac volutpat enim tincidunt quis. Cras ornare magna vitae egestas convallis. Proin a erat sed lorem lacinia dictum ut et lorem. Donec dapibus sagittis ipsum, vel iaculis ante ultricies tincidunt. Nunc elementum nisl sed enim tempus mattis. Sed finibus nec lectus sed tristique.\r\n\r\nPhasellus eros est, dapibus sed vulputate non, laoreet ac odio. Vivamus venenatis auctor ultrices. Phasellus vestibulum porta elit, id gravida sem ultricies et. Aliquam quis ex vel eros finibus porttitor. Fusce eu rutrum quam. Nunc vel nisl leo. Phasellus scelerisque convallis est, vel varius lectus molestie quis. Pellentesque non tempus lorem. Proin interdum dui vel urna ultricies faucibus. Suspendisse turpis est, varius ut nibh vel, posuere tempor risus. Nulla scelerisque dictum congue.\r\n\r\nDuis id elementum magna, vel viverra nisl. In posuere et lorem vitae iaculis. Mauris et dapibus massa, ac tempus arcu. Donec eu ipsum vitae lorem elementum varius. Fusce egestas est tortor, eget egestas massa tristique id. Sed eu pellentesque neque. Praesent in lacus sem. Maecenas lobortis porttitor magna ac elementum. Praesent laoreet turpis eu enim placerat vestibulum. Ut eleifend fringilla massa ut porttitor. Integer pretium purus nec vulputate gravida. Curabitur mattis tincidunt ipsum, ac rutrum erat egestas vestibulum.', 'education', '1759646867_buku.jpg'),
(14, 'Aliquam Euismod Venenatis Justo Non Tincidunt', '2025-10-05 12:41:55', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed hendrerit dui sed odio elementum, et lacinia ipsum posuere. Pellentesque tortor ex, fringilla eget auctor nec, efficitur id quam. Nulla facilisi. Morbi in auctor dolor, porttitor posuere tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer lobortis scelerisque urna. Pellentesque volutpat mauris quis arcu cursus sollicitudin.\r\n\r\nInteger cursus eget lacus sit amet porttitor. Mauris tristique elementum ante et maximus. Duis egestas tempus ante, et vestibulum metus sollicitudin vitae. Quisque faucibus mauris neque, ut venenatis libero vehicula quis. Quisque maximus turpis neque, et tempus velit tempus eu. Aliquam euismod venenatis justo non tincidunt. Donec ornare, elit sed condimentum congue, turpis odio dapibus felis, et varius enim odio ut lacus. Vestibulum id leo quis sem pulvinar sollicitudin vel nec ante. Pellentesque quis euismod lacus, non sodales urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer hendrerit in elit eu aliquam. Vivamus et commodo arcu, ac facilisis ipsum. Sed non suscipit risus, et lacinia justo. Fusce vel ipsum lacus.\r\n\r\nDonec dictum dui diam, tristique mollis justo fermentum in. Donec in leo tellus. Nunc efficitur tortor ut nisl laoreet, quis rutrum ipsum varius. Nunc ullamcorper lobortis neque, ac volutpat enim tincidunt quis. Cras ornare magna vitae egestas convallis. Proin a erat sed lorem lacinia dictum ut et lorem. Donec dapibus sagittis ipsum, vel iaculis ante ultricies tincidunt. Nunc elementum nisl sed enim tempus mattis. Sed finibus nec lectus sed tristique.\r\n\r\nPhasellus eros est, dapibus sed vulputate non, laoreet ac odio. Vivamus venenatis auctor ultrices. Phasellus vestibulum porta elit, id gravida sem ultricies et. Aliquam quis ex vel eros finibus porttitor. Fusce eu rutrum quam. Nunc vel nisl leo. Phasellus scelerisque convallis est, vel varius lectus molestie quis. Pellentesque non tempus lorem. Proin interdum dui vel urna ultricies faucibus. Suspendisse turpis est, varius ut nibh vel, posuere tempor risus. Nulla scelerisque dictum congue.\r\n\r\nDuis id elementum magna, vel viverra nisl. In posuere et lorem vitae iaculis. Mauris et dapibus massa, ac tempus arcu. Donec eu ipsum vitae lorem elementum varius. Fusce egestas est tortor, eget egestas massa tristique id. Sed eu pellentesque neque. Praesent in lacus sem. Maecenas lobortis porttitor magna ac elementum. Praesent laoreet turpis eu enim placerat vestibulum. Ut eleifend fringilla massa ut porttitor. Integer pretium purus nec vulputate gravida. Curabitur mattis tincidunt ipsum, ac rutrum erat egestas vestibulum.', 'coding', '1759646852_kotlin.webp'),
(15, 'Vestibulum Id Leo Quis Sem Pulvinar Sollicitudin Vel Nec Ante', '2025-10-05 12:44:58', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed hendrerit dui sed odio elementum, et lacinia ipsum posuere. Pellentesque tortor ex, fringilla eget auctor nec, efficitur id quam. Nulla facilisi. Morbi in auctor dolor, porttitor posuere tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer lobortis scelerisque urna. Pellentesque volutpat mauris quis arcu cursus sollicitudin.\r\n\r\nInteger cursus eget lacus sit amet porttitor. Mauris tristique elementum ante et maximus. Duis egestas tempus ante, et vestibulum metus sollicitudin vitae. Quisque faucibus mauris neque, ut venenatis libero vehicula quis. Quisque maximus turpis neque, et tempus velit tempus eu. Aliquam euismod venenatis justo non tincidunt. Donec ornare, elit sed condimentum congue, turpis odio dapibus felis, et varius enim odio ut lacus. Vestibulum id leo quis sem pulvinar sollicitudin vel nec ante. Pellentesque quis euismod lacus, non sodales urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer hendrerit in elit eu aliquam. Vivamus et commodo arcu, ac facilisis ipsum. Sed non suscipit risus, et lacinia justo. Fusce vel ipsum lacus.\r\n\r\nDonec dictum dui diam, tristique mollis justo fermentum in. Donec in leo tellus. Nunc efficitur tortor ut nisl laoreet, quis rutrum ipsum varius. Nunc ullamcorper lobortis neque, ac volutpat enim tincidunt quis. Cras ornare magna vitae egestas convallis. Proin a erat sed lorem lacinia dictum ut et lorem. Donec dapibus sagittis ipsum, vel iaculis ante ultricies tincidunt. Nunc elementum nisl sed enim tempus mattis. Sed finibus nec lectus sed tristique.\r\n\r\nPhasellus eros est, dapibus sed vulputate non, laoreet ac odio. Vivamus venenatis auctor ultrices. Phasellus vestibulum porta elit, id gravida sem ultricies et. Aliquam quis ex vel eros finibus porttitor. Fusce eu rutrum quam. Nunc vel nisl leo. Phasellus scelerisque convallis est, vel varius lectus molestie quis. Pellentesque non tempus lorem. Proin interdum dui vel urna ultricies faucibus. Suspendisse turpis est, varius ut nibh vel, posuere tempor risus. Nulla scelerisque dictum congue.\r\n\r\nDuis id elementum magna, vel viverra nisl. In posuere et lorem vitae iaculis. Mauris et dapibus massa, ac tempus arcu. Donec eu ipsum vitae lorem elementum varius. Fusce egestas est tortor, eget egestas massa tristique id. Sed eu pellentesque neque. Praesent in lacus sem. Maecenas lobortis porttitor magna ac elementum. Praesent laoreet turpis eu enim placerat vestibulum. Ut eleifend fringilla massa ut porttitor. Integer pretium purus nec vulputate gravida. Curabitur mattis tincidunt ipsum, ac rutrum erat egestas vestibulum.', 'travel', '1759646839_sardinia.avif'),
(16, 'In Posuere Et Lorem Vitae Iaculis', '2025-10-05 12:48:43', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed hendrerit dui sed odio elementum, et lacinia ipsum posuere. Pellentesque tortor ex, fringilla eget auctor nec, efficitur id quam. Nulla facilisi. Morbi in auctor dolor, porttitor posuere tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer lobortis scelerisque urna. Pellentesque volutpat mauris quis arcu cursus sollicitudin.\r\n\r\nInteger cursus eget lacus sit amet porttitor. Mauris tristique elementum ante et maximus. Duis egestas tempus ante, et vestibulum metus sollicitudin vitae. Quisque faucibus mauris neque, ut venenatis libero vehicula quis. Quisque maximus turpis neque, et tempus velit tempus eu. Aliquam euismod venenatis justo non tincidunt. Donec ornare, elit sed condimentum congue, turpis odio dapibus felis, et varius enim odio ut lacus. Vestibulum id leo quis sem pulvinar sollicitudin vel nec ante. Pellentesque quis euismod lacus, non sodales urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer hendrerit in elit eu aliquam. Vivamus et commodo arcu, ac facilisis ipsum. Sed non suscipit risus, et lacinia justo. Fusce vel ipsum lacus.\r\n\r\nDonec dictum dui diam, tristique mollis justo fermentum in. Donec in leo tellus. Nunc efficitur tortor ut nisl laoreet, quis rutrum ipsum varius. Nunc ullamcorper lobortis neque, ac volutpat enim tincidunt quis. Cras ornare magna vitae egestas convallis. Proin a erat sed lorem lacinia dictum ut et lorem. Donec dapibus sagittis ipsum, vel iaculis ante ultricies tincidunt. Nunc elementum nisl sed enim tempus mattis. Sed finibus nec lectus sed tristique.\r\n\r\nPhasellus eros est, dapibus sed vulputate non, laoreet ac odio. Vivamus venenatis auctor ultrices. Phasellus vestibulum porta elit, id gravida sem ultricies et. Aliquam quis ex vel eros finibus porttitor. Fusce eu rutrum quam. Nunc vel nisl leo. Phasellus scelerisque convallis est, vel varius lectus molestie quis. Pellentesque non tempus lorem. Proin interdum dui vel urna ultricies faucibus. Suspendisse turpis est, varius ut nibh vel, posuere tempor risus. Nulla scelerisque dictum congue.\r\n\r\nDuis id elementum magna, vel viverra nisl. In posuere et lorem vitae iaculis. Mauris et dapibus massa, ac tempus arcu. Donec eu ipsum vitae lorem elementum varius. Fusce egestas est tortor, eget egestas massa tristique id. Sed eu pellentesque neque. Praesent in lacus sem. Maecenas lobortis porttitor magna ac elementum. Praesent laoreet turpis eu enim placerat vestibulum. Ut eleifend fringilla massa ut porttitor. Integer pretium purus nec vulputate gravida. Curabitur mattis tincidunt ipsum, ac rutrum erat egestas vestibulum.', 'travel', '1759646821_museum.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `iduser` int(11) NOT NULL,
  `email` varchar(20) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`iduser`, `email`, `password`) VALUES
(6, 'juki@email.com', '$2y$10$3FyQPbHnkU5oiIBfx/RVnO3PPgyaBkC.RCzcxxHhzuWcZWhGyX5Xm');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `article`
--
ALTER TABLE `article`
  ADD PRIMARY KEY (`idarticle`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`iduser`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `article`
--
ALTER TABLE `article`
  MODIFY `idarticle` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `iduser` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
